package com.andrs002.networkdiagnostic

import android.Manifest
import android.content.Context
import android.content.Intent
import android.os.Build
import android.content.pm.PackageManager
import android.graphics.Color
import android.net.*
import android.os.Bundle
import android.telephony.*
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import java.net.HttpURLConnection
import java.net.InetAddress
import java.net.InetSocketAddress
import java.net.Socket
import java.net.URL
import java.text.SimpleDateFormat
import java.util.*
import java.util.concurrent.*
import java.util.concurrent.atomic.AtomicBoolean

class MainActivity : AppCompatActivity() {
    private lateinit var output:TextView; private lateinit var runButton:Button; private lateinit var stopButton:Button; private lateinit var grantButton:Button; private lateinit var resetNowButton:Button; private lateinit var telemetry:TelemetryUploader; private lateinit var shizukuRecovery:ShizukuRecovery
    private val executor=Executors.newSingleThreadScheduledExecutor(); private val uploadExecutor=Executors.newSingleThreadExecutor(); private var monitor:ScheduledFuture<*>?=null
    private val cycling=AtomicBoolean(false);@Volatile private var lastDataCycleAt=0L
    private val lines=ArrayDeque<String>(); private var sample=0; @Volatile private var netEvent="INIT"; private var failureStartedAt:Long?=null; private var recoveryAttempts=0; private var nextRecoveryAt=0L; private var recoveryCallback:ConnectivityManager.NetworkCallback?=null
    private var lastGoodCell=""; private var lastDnsOk=true; private var lastHttpsOk=true; @Volatile private var lastRegisteredAt=0L
    private fun now()=SimpleDateFormat("HH:mm:ss.SSS",Locale.US).format(Date())
    @Synchronized private fun appendLine(s:String){lines.addLast(s);while(lines.size>1200)lines.removeFirst()}
    @Synchronized private fun currentLog()=lines.joinToString("\n")
    private fun callbackEvent(s:String){netEvent=s;appendLine("EVENT,${now()},${s.replace(',',';')}")}
    private fun uploadSnapshot(summary:String){telemetry.enqueue(summary,currentLog());uploadExecutor.execute{appendLine("TELEMETRY,${now()},${telemetry.flush()}")}}

    override fun onCreate(b:Bundle?){super.onCreate(b);telemetry=TelemetryUploader(applicationContext);val d=resources.displayMetrics.density;val p=(16*d).toInt();val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(p,p,p,p)}
        runButton=Button(this).apply{text="開始網路診斷與自動補救 v11";textSize=18f;setTextColor(Color.WHITE);setBackgroundColor(Color.rgb(0,100,200));isAllCaps=false;layoutParams=LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,(72*d).toInt()).apply{bottomMargin=p}}
        stopButton=Button(this).apply{text="停止監測";isAllCaps=false;isEnabled=false};output=TextView(this).apply{text="Network Diagnostic v11\n真正的行動數據重連需啟用 Shizuku。未授權時僅診斷，不會假裝已修復。";textSize=14f;setTextIsSelectable(true)};grantButton=Button(this).apply{text="授權 Shizuku：啟用真正的數據重連";isAllCaps=false};resetNowButton=Button(this).apply{text="立即重連行動數據（Shizuku）";isAllCaps=false};box.addView(grantButton);box.addView(resetNowButton);box.addView(runButton);box.addView(stopButton);box.addView(output);setContentView(ScrollView(this).apply{addView(box)});runButton.setOnClickListener{permissionsAndRun()};stopButton.setOnClickListener{stopMonitor()};shizukuRecovery=ShizukuRecovery(this){ msg-> appendLine("SHIZUKU,"+now()+","+msg);uploadSnapshot("SHIZUKU:"+msg) };grantButton.setOnClickListener{shizukuRecovery.requestEnable()};resetNowButton.setOnClickListener{if(!shizukuRecovery.enabled){Toast.makeText(this,"請先啟動並授權 Shizuku",Toast.LENGTH_LONG).show()}else{executor.execute{val result=performDataCycle("MANUAL");appendLine("MANUAL,"+now()+","+result);runOnUiThread{output.text=currentLog().takeLast(60000)}}}}}
    private fun permissionsAndRun(){val p=arrayOf(Manifest.permission.READ_PHONE_STATE,Manifest.permission.ACCESS_FINE_LOCATION);val m=p.filter{ActivityCompat.checkSelfPermission(this,it)!=PackageManager.PERMISSION_GRANTED};if(m.isNotEmpty())ActivityCompat.requestPermissions(this,m.toTypedArray(),9)else startMonitor()}
    override fun onRequestPermissionsResult(r:Int,p:Array<out String>,g:IntArray){super.onRequestPermissionsResult(r,p,g);if(r==9&&g.all{it==PackageManager.PERMISSION_GRANTED})startMonitor()}

    private val defaultCallback=object:ConnectivityManager.NetworkCallback(){
        override fun onAvailable(n:Network)=callbackEvent("AVAILABLE:$n"); override fun onLost(n:Network)=callbackEvent("LOST:$n")
        override fun onCapabilitiesChanged(n:Network,c:NetworkCapabilities)=callbackEvent("CAP:$n:CELL=${c.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)}:VALID=${c.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)}:INTERNET=${c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)}:SUSP=${!c.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_SUSPENDED)}")
        override fun onLinkPropertiesChanged(n:Network,lp:LinkProperties)=callbackEvent("LINK:$n:${linkSummary(lp)}")}
    private fun linkSummary(lp:LinkProperties?):String{if(lp==null)return "LP=null";return "IF=${lp.interfaceName}:ADDR=${lp.linkAddresses.joinToString("+")}:DNS=${lp.dnsServers.joinToString("+")}:ROUTES=${lp.routes.joinToString("+"){it.toString()}}"}
    private fun networkSummary(cm:ConnectivityManager,n:Network?):String{if(n==null)return "NET=null";val c=cm.getNetworkCapabilities(n);val lp=cm.getLinkProperties(n);return "NET=$n:CELL=${c?.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)}:VALID=${c?.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)}:INTERNET=${c?.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)}:SUSP=${c?.let{!it.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_SUSPENDED)}}:${linkSummary(lp)}"}

    private fun startMonitor(){
        val serviceIntent=Intent(this,NetworkMonitorService::class.java)
        if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O) startForegroundService(serviceIntent) else startService(serviceIntent)
        monitor?.cancel(false);synchronized(this){lines.clear()};sample=0;failureStartedAt=null;recoveryAttempts=0;nextRecoveryAt=0;lastGoodCell="";lastDnsOk=true;lastHttpsOk=true;lastRegisteredAt=System.currentTimeMillis();val cm=getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager;try{cm.unregisterNetworkCallback(defaultCallback)}catch(_:Exception){};cm.bindProcessToNetwork(null);cm.registerDefaultNetworkCallback(defaultCallback);appendLine("=== Network Diagnostic v11: opt-in Shizuku data-cycle ===");appendLine("SAMPLE,time,n,transport,rat,voiceReg,dataState,event,registered,pci,earfcn,band,tac,ci,rsrp,rsrq,rssi,sinr,dns,https,recovery");runButton.isEnabled=false;stopButton.isEnabled=true;monitor=executor.scheduleAtFixedRate({takeSample()},0,1,TimeUnit.SECONDS);uploadSnapshot("MONITOR_STARTED_V11")}

    private fun requestCellularRecovery(reason:String):String{val cm=getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager;recoveryAttempts++;val a=recoveryAttempts;nextRecoveryAt=System.currentTimeMillis()+10000;cm.bindProcessToNetwork(null);recoveryCallback?.let{try{cm.unregisterNetworkCallback(it)}catch(_:Exception){}};recoveryCallback=null
        appendLine("RECOVERY,${now()},RESET_OLD_REQUEST,attempt=$a");appendLine("RECOVERY,${now()},REQUEST_CELLULAR,attempt=$a,reason=$reason");uploadSnapshot("REQUEST_CELLULAR#$a:$reason")
        val cb=object:ConnectivityManager.NetworkCallback(){override fun onAvailable(n:Network){appendLine("RECOVERY,${now()},CELLULAR_AVAILABLE,attempt=$a,${networkSummary(cm,n)}");executor.execute{deepProbe(n,a)}};override fun onCapabilitiesChanged(n:Network,c:NetworkCapabilities){appendLine("RECOVERY,${now()},RECOVERY_CAP,attempt=$a,${networkSummary(cm,n)}")};override fun onLinkPropertiesChanged(n:Network,lp:LinkProperties){appendLine("RECOVERY,${now()},RECOVERY_LINK,attempt=$a,${linkSummary(lp)}")};override fun onLost(n:Network){appendLine("RECOVERY,${now()},RECOVERY_NETWORK_LOST,attempt=$a,network=$n")};override fun onUnavailable(){appendLine("RECOVERY,${now()},UNAVAILABLE,attempt=$a")}}
        recoveryCallback=cb;val req=NetworkRequest.Builder().addTransportType(NetworkCapabilities.TRANSPORT_CELLULAR).addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET).build();try{cm.requestNetwork(req,cb,10000)}catch(e:Exception){appendLine("RECOVERY,${now()},REQUEST_FAILED,attempt=$a,${e.javaClass.simpleName}:${e.message}")};return "REQUEST_CELLULAR#$a"}

    private fun performDataCycle(source:String):String{if(!cycling.compareAndSet(false,true))return "SKIPPED_ALREADY_CYCLING";try{val t=System.currentTimeMillis();if(t-lastDataCycleAt<180000)return "SKIPPED_COOLDOWN";val tm=getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager;val busy=try{tm.callState!=TelephonyManager.CALL_STATE_IDLE}catch(_:Exception){true};if(busy)return "SKIPPED_ACTIVE_CALL";if(!shizukuRecovery.enabled)return "SKIPPED_SHIZUKU_NOT_READY";lastDataCycleAt=t;appendLine("RECOVERY,"+now()+",DATA_CYCLE_START,source="+source);uploadSnapshot("DATA_CYCLE_START:"+source);val result=shizukuRecovery.cycle();appendLine("RECOVERY,"+now()+","+result);uploadSnapshot("DATA_CYCLE_RESULT:"+result);return result}finally{cycling.set(false)}}

    private fun deepProbe(n:Network,a:Int){val cm=getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager;appendLine("DEEP,${now()},attempt=$a,${networkSummary(cm,n)}")
        try{val ips=n.getAllByName("www.google.com");appendLine("DEEP,${now()},DNS_OK,attempt=$a,${ips.joinToString("+"){it.hostAddress?:"?"}}") }catch(e:Exception){appendLine("DEEP,${now()},DNS_FAIL,attempt=$a,${e.javaClass.simpleName}:${e.message}")}
        try{val s=n.socketFactory.createSocket() as Socket;s.connect(InetSocketAddress("1.1.1.1",443),3500);appendLine("DEEP,${now()},IPV4_SOCKET_OK,attempt=$a,remote=1.1.1.1:443");s.close()}catch(e:Exception){appendLine("DEEP,${now()},IPV4_SOCKET_FAIL,attempt=$a,${e.javaClass.simpleName}:${e.message}")}
        try{val h=n.openConnection(URL("https://www.google.com/generate_204")) as HttpURLConnection;h.connectTimeout=4000;h.readTimeout=4000;h.useCaches=false;val code=h.responseCode;appendLine("DEEP,${now()},BOUND_HTTPS,attempt=$a,code=$code");h.disconnect()}catch(e:Exception){appendLine("DEEP,${now()},BOUND_HTTPS_FAIL,attempt=$a,${e.javaClass.simpleName}:${e.message}")}
        uploadSnapshot("DEEP_PROBE#$a")}

    private fun recoveryState(reg:Boolean,tr:String,dns:Boolean,https:Boolean,cell:String):String{val t=System.currentTimeMillis();if(reg){lastRegisteredAt=t;if(cell.isNotBlank())lastGoodCell=cell};if(tr=="WIFI"){if(failureStartedAt!=null){appendLine("RECOVERY,${now()},CANCELLED_WIFI_ACTIVE,attempts=$recoveryAttempts");uploadSnapshot("RECOVERY_CANCELLED_WIFI_ACTIVE")};failureStartedAt=null;recoveryAttempts=0;nextRecoveryAt=0;recoveryCallback?.let{try{(getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager).unregisterNetworkCallback(it)}catch(_:Exception){}};recoveryCallback=null;return "WIFI_ACTIVE"};val cellInfoStale=!reg && (t-lastRegisteredAt)>5000;val br=tr=="NONE";val bd=!dns||!https;val bad=bd||br;if(!bad){failureStartedAt?.let{val sec=(t-it)/1000;appendLine("RECOVERY,${now()},RECOVERED,${sec}s,attempts=$recoveryAttempts,cell=$cell");uploadSnapshot("RECOVERED:${sec}s:attempts=$recoveryAttempts");failureStartedAt=null;recoveryAttempts=0;nextRecoveryAt=0;(getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager).bindProcessToNetwork(null);return "RECOVERED:${sec}s"};return "OK"};if(failureStartedAt==null){failureStartedAt=t;nextRecoveryAt=t+12000;appendLine("RECOVERY,${now()},FAILURE_START,radio=$br,data=$bd,lastCell=$lastGoodCell");uploadSnapshot("FAILURE_START:radio=$br:data=$bd");return "FAILURE_START"};val sec=(t-failureStartedAt!!)/1000;if(t>=nextRecoveryAt){nextRecoveryAt=t+180000;val tm=getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager;val onCall=try{tm.callState!=TelephonyManager.CALL_STATE_IDLE}catch(_:Exception){true};if(onCall){appendLine("RECOVERY,"+now()+",SKIP_ACTIVE_CALL");return "SKIP_ACTIVE_CALL"};if(!shizukuRecovery.enabled){appendLine("RECOVERY,"+now()+",SHIZUKU_NOT_AUTHORIZED_NO_REPAIR");uploadSnapshot("RECOVERY_UNAVAILABLE:SHIZUKU_NOT_AUTHORIZED");return "NO_PRIVILEGED_RECOVERY"};val result=performDataCycle("AUTO");return if(result.startsWith("DATA_CYCLE_CMD:"))"DATA_CYCLE_ATTEMPTED" else result};return "WAIT:${sec}s"}

    private fun takeSample(){sample++;var tr="NONE";var rat="?";var voice="?";var ds="?";var reg=false;var pci="";var ef="";var band="";var tac="";var ci="";var rsrp="";var rsrq="";var rssi="";var sinr="";var dns="-";var https="-";var dok=lastDnsOk;var hok=lastHttpsOk
        try{val cm=getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager;val active=cm.activeNetwork;val caps=cm.getNetworkCapabilities(active);tr=when{caps?.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)==true->"CELLULAR";caps?.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)==true->"WIFI";else->"NONE"};if(sample%5==0)appendLine("STATE,${now()},${networkSummary(cm,active)}");val tm=getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager;rat=when(tm.dataNetworkType){TelephonyManager.NETWORK_TYPE_LTE->"LTE";TelephonyManager.NETWORK_TYPE_NR->"NR";else->tm.dataNetworkType.toString()};voice=when(tm.serviceState?.state){ServiceState.STATE_IN_SERVICE->"IN";ServiceState.STATE_OUT_OF_SERVICE->"OUT";ServiceState.STATE_EMERGENCY_ONLY->"EMERGENCY";ServiceState.STATE_POWER_OFF->"OFF";else->"?"};ds=when(tm.dataState){TelephonyManager.DATA_CONNECTED->"CONNECTED";TelephonyManager.DATA_CONNECTING->"CONNECTING";TelephonyManager.DATA_DISCONNECTED->"DISCONNECTED";TelephonyManager.DATA_SUSPENDED->"SUSPENDED";else->tm.dataState.toString()};when(val s=tm.allCellInfo?.firstOrNull{it.isRegistered}){is CellInfoLte->{val x=s.cellSignalStrength;val id=s.cellIdentity;reg=true;pci=id.pci.toString();ef=id.earfcn.toString();band=try{id.bands.joinToString("+")}catch(_:Exception){""};tac=id.tac.toString();ci=id.ci.toString();rsrp=x.rsrp.toString();rsrq=x.rsrq.toString();rssi=x.rssi.toString();sinr=x.rssnr.toString()};is CellInfoNr->{val x=s.cellSignalStrength as CellSignalStrengthNr;val id=s.cellIdentity as CellIdentityNr;reg=true;pci=id.pci.toString();ef=id.nrarfcn.toString();band=try{id.bands.joinToString("+")}catch(_:Exception){""};tac=id.tac.toString();ci=id.nci.toString();rsrp=x.ssRsrp.toString();rsrq=x.ssRsrq.toString();sinr=x.ssSinr.toString()}}
            if(sample%5==0){val td=System.nanoTime();try{val a=InetAddress.getAllByName("www.google.com");dok=true;dns="OK:${(System.nanoTime()-td)/1_000_000}ms:${a.firstOrNull()?.hostAddress}"}catch(e:Exception){dok=false;dns="FAIL:${e.javaClass.simpleName}"};lastDnsOk=dok;val th=System.nanoTime();try{val h=URL("https://www.google.com/generate_204").openConnection() as HttpURLConnection;h.connectTimeout=4000;h.readTimeout=4000;h.useCaches=false;val code=h.responseCode;hok=code in 200..399;https="$code:${(System.nanoTime()-th)/1_000_000}ms";h.disconnect()}catch(e:Exception){hok=false;https="FAIL:${e.javaClass.simpleName}"};lastHttpsOk=hok}}
        catch(e:Exception){hok=false;lastHttpsOk=false;https="ERR:${e.javaClass.simpleName}"};val cell="$pci/$ef/$ci";val rec=recoveryState(reg,tr,dok,hok,cell);appendLine("SAMPLE,${now()},$sample,$tr,$rat,$voice,$ds,${netEvent.replace(',',';')},$reg,$pci,$ef,$band,$tac,$ci,$rsrp,$rsrq,$rssi,$sinr,$dns,$https,$rec");if(sample%10==0)uploadSnapshot("LIVE_STATUS:$tr:$rat:reg=$reg:pci=$pci:earfcn=$ef:band=$band:rsrp=$rsrp:rsrq=$rsrq:sinr=$sinr:dns=$dns:https=$https:recovery=$rec");val text=currentLog();runOnUiThread{output.text=text.takeLast(60000)}}

    private fun stopMonitor(){stopService(Intent(this,NetworkMonitorService::class.java));monitor?.cancel(false);monitor=null;val cm=getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager;try{cm.unregisterNetworkCallback(defaultCallback)}catch(_:Exception){};recoveryCallback?.let{try{cm.unregisterNetworkCallback(it)}catch(_:Exception){}};recoveryCallback=null;cm.bindProcessToNetwork(null);uploadSnapshot("MONITOR_STOPPED_V11");runButton.isEnabled=true;stopButton.isEnabled=false;output.text=currentLog().takeLast(60000)}
    override fun onDestroy(){stopMonitor();shizukuRecovery.close();executor.shutdownNow();uploadExecutor.shutdown();super.onDestroy()}
}
